# Generated by Django 6.0.3 on 2026-03-22 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.CharField(max_length=50, unique=True)),
                ("modele", models.CharField(max_length=100)),
                (
                    "niveau_batterie",
                    models.FloatField(
                        help_text="Niveau de batterie en pourcentage (0-100)"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_vol", "En vol"),
                            ("maintenance", "En maintenance"),
                            ("hors_service", "Hors service"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mot_de_passe", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("operateur", "Opérateur drone"),
                            ("superviseur", "Superviseur logistique"),
                            ("planificateur", "Planificateur"),
                            ("administrateur", "Administrateur"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_heure", models.DateTimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="planifiee",
                        max_length=20,
                    ),
                ),
                ("trajectoire", models.TextField(blank=True)),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="missions",
                        to="drones.drone",
                    ),
                ),
                (
                    "operateur",
                    models.ForeignKey(
                        limit_choices_to={"role": "operateur"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="missions_operateur",
                        to="drones.utilisateur",
                    ),
                ),
                (
                    "planificateur",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "planificateur"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="missions_planificateur",
                        to="drones.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_anomalie",
                    models.CharField(
                        choices=[
                            ("batterie", "Batterie faible"),
                            ("obstacle", "Obstacle détecté"),
                            ("deviation", "Déviation de trajectoire"),
                            ("connexion", "Perte de connexion"),
                            ("autre", "Autre anomalie"),
                        ],
                        max_length=30,
                    ),
                ),
                ("horodatage", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("nouvelle", "Nouvelle"),
                            ("en_traitement", "En traitement"),
                            ("resolue", "Résolue"),
                        ],
                        default="nouvelle",
                        max_length=20,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes",
                        to="drones.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RapportAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_rapport", models.DateTimeField(auto_now_add=True)),
                (
                    "mission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rapport",
                        to="drones.mission",
                    ),
                ),
                (
                    "superviseur",
                    models.ForeignKey(
                        limit_choices_to={"role": "superviseur"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rapports",
                        to="drones.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EcartInventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "rapport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ecarts",
                        to="drones.rapportaudit",
                    ),
                ),
            ],
        ),
    ]
